schema_version: "1.0"
name: "gdpr-transforms"
models:
  - transforms:
      data_source: "_"
      use_nlp: False
      policies:
        - name: deidentify_pii
          transform_attrs:
            locales:
              - en_US
          rules:
            - name: fake email
              conditions:
                field_label:
                  - email_address
              transforms:
                - type: fake
                  attrs:
                    method: email
                    params: {domain: foo.com}
            - name: city
              conditions:
                field_name_regex:
                  - '(?i)^((city|metropolitan|metro)[\ ,-,_,\.]*(name|area)|city|cities|town|township|capital|municipality|city\/town|town\/city)[s,es,\(s\),:,-]*$'
              transforms:
                - type: passthrough
            - name: state
              conditions:
                field_name_regex:
                  - '(?i)^(state|province|state\/province|province\/state)[s,es,\(s\),:,-]*$'
              transforms:
                - type: passthrough
            - name: country
              conditions:
                field_name_regex:
                  - '(?i)^(country[\/\ ,-,_,\.]*(name|region|territory)|country|countries)[s,\(s\),:,-]*$'
              transforms:
                - type: passthrough            
            - name: last_name
              conditions:
                field_name_regex:
                  - '(?i)^((last|family)[\ ,-,_,\.]*name|lname|surname|last|byname)[s,\(s\),:,-]*$'
              transforms:
                - type: fake
                  attrs:
                    method: name_nonbinary
            - name: first_name
              conditions:
                field_name_regex:
                  - '(?i)^((first|nick|given|middle)[\ ,-,_,\.]*name|fname|given|first|middle)[s,\(s\),:,-]*$'
              transforms:
                - type: fake
                  attrs:
                    method: first_name_nonbinary
            - name: street_address
              conditions:
                field_name_regex:
                  - '(?i)^((street|home|business)[\,-,_,\.]*address|street|address|headquarters|home|residence)[s,es,\(s\),:,-]*$'
              transforms:
                - type: fake
                  attrs:
                    method: street_address
            - name: fake_or_redact_pii
              conditions:
                field_label:
                  - person_name
                  - credit_card_number
                  - phone_number
                  - phone_number_namer
                  - us_social_security_number
                  - ip_address
                  - credit_card_number
                  - imei_hardware_id
                  - imsi_subscriber_id
              transforms:
                - type: fake
                - type: redact_with_char
                  attrs:
                    char: X
        - name: hash_ids
          rules:
            - name: hash_ids
              conditions:
                field_name_regex:
                  - '(?i)^.*[ _.-]id$'
                field_name:
                  - id
                field_label:
                  - uuid
                  - md5
                  - sha256
                  - sha512
                field_attributes:
                  is_id: true
              transforms:
                - type: hash
                  attrs:
                    length: 8
label_predictors:
  namespace: gdpr
  # If >= 80% of the values in a field / column
  # match any single entity, classify the entire field / column
  # with that label. When using `field_label` conditions over
  # `field_value` conditions, which search each field, this
  # can drastically speed up data transformation.
  field_label_threshold: 0.80